"""add file_url to assignment

Revision ID: 58e8c63d8433
Revises: fbaf0d6f39e4
Create Date: 2026-06-03 09:41:52.592137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e8c63d8433'
down_revision = 'fbaf0d6f39e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###
