"""create batches table

Revision ID: 6a3195a6c91a
Revises: c6eaf77d1abb
Create Date: 2026-05-26 20:04:48.461127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a3195a6c91a'
down_revision = 'c6eaf77d1abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=150), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('days', sa.String(length=150), nullable=True),
    sa.Column('start_time', sa.String(length=50), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('classroom', sa.String(length=100), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=True),
    sa.Column('filled_seats', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Float(), nullable=True),
    sa.Column('monthly_fee', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batches')
    # ### end Alembic commands ###
