"""create courses table

Revision ID: c6eaf77d1abb
Revises: 6178a6586c2e
Create Date: 2026-05-26 09:28:44.624682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6eaf77d1abb'
down_revision = '6178a6586c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('duration', sa.String(length=150), nullable=True),
    sa.Column('mode', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('certificate_available', sa.Boolean(), nullable=True),
    sa.Column('placement_support', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    # ### end Alembic commands ###
