"""add student login fields

Revision ID: fbaf0d6f39e4
Revises: e2d4596bbd2f
Create Date: 2026-06-02 11:54:16.827263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaf0d6f39e4'
down_revision = 'e2d4596bbd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_login_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('is_login_enabled')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
